name: Build BLM RSS (Keywords)

on:
  push:
  schedule:
    - cron: "0 */3 * * *"  # every 3 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build RSS
        run: npm run build

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "update RSS $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
